name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poly/ML
        run: apt-get install polyml

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./test.sh
